[general]
import = [ "~/.themes/catppuccin/alacritty/catppuccin/catppuccin-macchiato.toml" ]

[font]
size = 10.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
startup_mode = "Windowed"
opacity = 0.9
padding = {x=2}
dimensions = { columns = 80, lines = 20}

[colors]
primary = { background = "#1E1E2E" }
